<a href="https://colab.research.google.com/github/NejiBuda/Python_Study/blob/main/Lesson_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1

Решите линейнную систему:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

Задание 2

Найдите псевдорешение:

x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [2]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]], float)
B = np.array([1, 7, 12, 7, 15])  
np.linalg.lstsq(A, B)[0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([ 1.13919353, -0.90498444, -0.9009803 ])

Задание 3

Сколько решений имеет линейная система:

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее

In [8]:
#Вычеслим определитель матрицы
 
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(b)

0.0

In [9]:
import matplotlib.pyplot as plt

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0, 0, 0]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


(2, 2)

Задние 4

Вычислите LU-разложение матрицы:

In [10]:
import scipy 
import scipy.linalg 

A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
L = np.array([ [1, 0, 0], [0.25, 1, 0], [0.5, -0.4, 1]])
U = np.array([ [4, 28, 73], [0, -5, -15.25], [0, 0, -21.6]])
A = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)

print("det A = ", np.linalg.det(A))
print("A = ", A)
print("P = ", P)
print("L = ", L)
print("U = ", U)

B = np.array([4, 1, 7])
np.linalg.solve(A, B)

det A =  432.00000000000017
A =  [[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]
P =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L =  [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U =  [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


array([ 0.28240741,  0.70601852, -0.23148148])

Задание 5

Найдите нормальное псевдорешение недоопределенной системы

x + 2y – z = 1

8x – 5y + 2z = 12

Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум

In [13]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

Задание 6

Найдите одно из псевдорешений вырожденной системы

Попробуйте также отыскать и нормальное псевдорешение

In [19]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [20]:
#Проверка правильности QR-разложения
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]


In [37]:
#Попробуем найти псевдорешение случайным образом 
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [40]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [41]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [24]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996